In [1]:
!pip install fpgrowth_py

Collecting fpgrowth_py
  Downloading fpgrowth_py-1.0.0-py3-none-any.whl (5.6 kB)
Installing collected packages: fpgrowth-py
Successfully installed fpgrowth-py-1.0.0

### Load the dataset

In [3]:
import pandas as pd

# data location:
path = '../data/'
file_name = 'Online Retail.xlsx'
sheet_name = 'Online Retail'
# read excel file
df = pd.read_excel(path + file_name, sheet_name=sheet_name)

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,`,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [32]:
unique_invoices = df.groupby(["InvoiceNo", "Country"]).size().reset_index()

# Top 3 countries by unique invoices
top_three_countries = unique_invoices['Country'].value_counts().nlargest(3)

top_three_countries = top_three_countries.index.values

top_three_countries

array(['United Kingdom', 'Germany', 'France'], dtype=object)

In [38]:
filtered_df = df.loc[df['Country'].isin(top_three_countries)]

filtered_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,`,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [40]:
filtered_df.drop(columns=['Quantity', "InvoiceDate", "UnitPrice", "CustomerID", "Country"], inplace=True)

filtered_df

/tmp/ipykernel_172654/2143584259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(columns=['Quantity', "InvoiceDate", "UnitPrice", "CustomerID", "Country"], inplace=True)

       InvoiceNo StockCode                          Description
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...       ...                                  ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[513530 rows x 3 columns]

In [82]:
grouped_invoices = filtered_df.set_index("Description").groupby("InvoiceNo").groups

grouped_invoices_list = [list(map(str, v.values)) for k,v in grouped_invoices.items()]

grouped_invoices_list[:3]

[['WHITE HANGING HEART T-LIGHT HOLDER',
  'WHITE METAL LANTERN',
  'CREAM CUPID HEARTS COAT HANGER',
  'KNITTED UNION FLAG HOT WATER BOTTLE',
  'RED WOOLLY HOTTIE WHITE HEART.',
  'SET 7 BABUSHKA NESTING BOXES',
  'GLASS STAR FROSTED T-LIGHT HOLDER'],
 ['HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT'],
 ['ASSORTED COLOUR BIRD ORNAMENT',
  "POPPY'S PLAYHOUSE BEDROOM ",
  "POPPY'S PLAYHOUSE KITCHEN",
  'FELTCRAFT PRINCESS CHARLOTTE DOLL',
  'IVORY KNITTED MUG COSY ',
  'BOX OF 6 ASSORTED COLOUR TEASPOONS',
  'BOX OF VINTAGE JIGSAW BLOCKS ',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'HOME BUILDING BLOCK WORD',
  'LOVE BUILDING BLOCK WORD',
  'RECIPE BOX WITH METAL HEART',
  'DOORMAT NEW ENGLAND']]

In [49]:
grouped_invoices = filtered_df.reset_index().set_index(["InvoiceNo", "StockCode"])

grouped_invoices

                      index                          Description
InvoiceNo StockCode
536365    85123A          0   WHITE HANGING HEART T-LIGHT HOLDER
          71053           1                  WHITE METAL LANTERN
          84406B          2       CREAM CUPID HEARTS COAT HANGER
          84029G          3  KNITTED UNION FLAG HOT WATER BOTTLE
          84029E          4       RED WOOLLY HOTTIE WHITE HEART.
...                     ...                                  ...
581587    22613      541904          PACK OF 20 SPACEBOY NAPKINS
          22899      541905         CHILDREN'S APRON DOLLY GIRL
          23254      541906        CHILDRENS CUTLERY DOLLY GIRL
          23255      541907      CHILDRENS CUTLERY CIRCUS PARADE
          22138      541908        BAKING SET 9 PIECE RETROSPOT

[513530 rows x 2 columns]

In [50]:
df.index

RangeIndex(start=0, stop=541909, step=1)

In [46]:
orders = [df.xs(level).values for level in df.index['InvoiceNo']]

orders

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [97]:
from fpgrowth_py import fpgrowth

freqItemSet, rules = fpgrowth(grouped_invoices_list, minSupRatio=0.01, minConf=0.6)

In [98]:
print(len(freqItemSet))

1207

In [103]:
filtered_sets = list(filter(lambda x: len(x) > 4,  freqItemSet))

print("FREQUENTLY ORDERED TOGETHER")

for item_set in filtered_sets:
    print("\n")
    print("\n  - ".join(list(item_set)))

FREQUENTLY ORDERED TOGETHER


CHARLOTTE BAG SUKI DESIGN
  - STRAWBERRY CHARLOTTE BAG
  - RED RETROSPOT CHARLOTTE BAG
  - CHARLOTTE BAG PINK POLKADOT
  - WOODLAND CHARLOTTE BAG